//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjModelFirstConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetail_Id { get; set; }
        public string ItemDescriptions { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int InvoiceHeaderInvoiceHeader_Id { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
